export const GET_INVENTORY = 'GET_INVENTORY'
export const ADD_TO_INVENTORY = 'ADD_TO_INVENTORY'
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY'

export const GET_EXECUTIVES = 'GET_EXECUTIVES'
export const ADD_TO_EXECUTIVES = 'ADD_TO_EXECUTIVES'
export const UPDATE_EXECUTIVES = 'UPDATE_EXECUTIVES'

export const CREATE_ORDER = 'CREATE_ORDER'

export const GET_ORDER = 'GET_ORDER'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const LOGOUT = 'LOGOUT'

export const USER_REQUEST = 'USER_REQUEST'
